#!/usr/bin/env node
/**
 * scripts/generate-config.js
 *
 * Reads SUPABASE_URL and SUPABASE_ANON_KEY and writes src/js/config.js.
 * Priority: process.env (Vercel) → .env file → .env.example file.
 * No external dotenv dependency required.
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname }            from 'path';
import { fileURLToPath }               from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root      = resolve(__dirname, '..');

/** Parse a .env-style file into process.env (existing keys take priority). */
function loadEnvFile(filePath) {
  try {
    const lines = readFileSync(filePath, 'utf8').split('\n');
    for (const raw of lines) {
      const line = raw.trim();
      if (!line || line.startsWith('#')) continue;
      const eq = line.indexOf('=');
      if (eq === -1) continue;
      const key = line.slice(0, eq).trim();
      const val = line.slice(eq + 1).trim();
      if (key && !(key in process.env)) {
        process.env[key] = val;
      }
    }
  } catch {
    // File doesn't exist — silently skip
  }
}

// Load in order: .env takes priority over .env.example
loadEnvFile(resolve(root, '.env'));
loadEnvFile(resolve(root, '.env.example'));

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_ANON_KEY;

if (!url || !key) {
  console.error('[WordDrop] ERROR: SUPABASE_URL or SUPABASE_ANON_KEY is missing.');
  console.error('  → Create a .env file (copy .env.example) and fill in your values.');
  process.exit(1);
}

const content = `// AUTO-GENERATED by scripts/generate-config.js — do not edit by hand.
export const SUPABASE_URL      = ${JSON.stringify(url)};
export const SUPABASE_ANON_KEY = ${JSON.stringify(key)};
`;

writeFileSync(resolve(root, 'src/js/config.js'), content, 'utf8');
console.log('[WordDrop] config.js written with real credentials.');
